spring:
  application:
    name: search-engine

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

crawler:
  max-depth: ${CRAWLER_MAX_DEPTH}
  user-agent: ${CRAWLER_USER_AGENT}
  timeout: ${CRAWLER_TIMEOUT}