spring:
  application:
    name: search-engine

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

crawler:
  max-depth: ${CRAWLER_MAX_DEPTH}
  user-agent: ${CRAWLER_USER_AGENT}
  timeout: ${CRAWLER_TIMEOUT}